### ISSUE TITLE
What is the rendener of math?

### ISSUE THREAD

**Issue by linwaytin** [mkhan45/CalcuLaTeX#34]
Thanks for this interesting work.
I'm curious about how you render the math.
Do you use some external library like pandoc? Or it's implement in the code?

**Comment by mkhan45** [comment]
The web site uses https://github.com/michael-brade/LaTeX.js, and the CLI uses Pandoc through https://github.com/oli-obk/rust-pandoc

**Comment by linwaytin** [comment]
Thank you!
