### ISSUE TITLE
Unit typesetting

### ISSUE THREAD

**Issue by ilyapopov** [mkhan45/CalcuLaTeX#35]
According to standards, units must be typeset in upright font. Consider typesetting units using `\mathrm{}` or even better, `siunitx` package if possible.

See for example [SI Brochure](https://www.bipm.org/en/publications/si-brochure/):

> Unit  symbols  are  written  using  roman  (upright)  type,  regardless  of  the  type  used  in  the  surrounding  text

**Comment by mkhan45** [comment]
That's actually something I was wondering about. Thanks for the advice! 

It should be fixed with f59f6fd.
