### ISSUE TITLE
Is there any plan to add saving notebooks?

### ISSUE THREAD

**Issue by SuspensionPoint** [mkhan45/CalcuLaTeX#48]
I'd really like to use this syntax for a math scratchpad. Is there any plans to continue developing on this project?

**Comment by mkhan45** [comment]
I'll definitely continue working on this for the next few months at least, although not as fast as the last few weeks.

What do you mean by saving notebooks?

**Comment by SuspensionPoint** [comment]
Really, I just want to use it as a scratch pad. If I close the tab now, I lose everything I wrote. Any way for that to persist would be super helpful.

**Comment by mkhan45** [comment]
As a stopgap, I think I can make the site save a basic cookie with the last input. Does that sound good to you?

Later on, I'm considering making a full website with user accounts, saved documents, easy collaboration/sharing calculations and whatever else seems useful. Just to get your opinion, would you pay something like $5 a month for such a service to cover hosting costs etc.? Everything would stay open source.

**Comment by SuspensionPoint** [comment]
That sounds great too me. Thank you!

**Comment by mkhan45** [comment]
Added a save cookie in https://github.com/mkhan45/CalcuLaTeX-Web/commit/131939a2e308c9d7adff4c4c4c65fcbae8d879b6.
