### ISSUE TITLE
Conversion Error Getting Degrees Instead of Grams

### ISSUE THREAD

**Issue by SymmetricChaos** [mkhan45/CalcuLaTeX#50]
'''
5 m/s^2 * 3 g = ?
'''
Give a result in (deg*m)/(s^2)

**Comment by mkhan45** [comment]
Funnily enough, that's correct although definitely should use some work. CalcuLaTeX doesn't actually have degrees, deg means decagrams.

I've considered just removing deca and hepto from possible output and adding an opt in later.

**Comment by SymmetricChaos** [comment]
I believe the SI convention is to use "dag" for decagram. The "deg" symbol is reversed for degrees, which are also an SI unit.

**Comment by mkhan45** [comment]
Alright here's what I'll do:

1. Switch de prefix to da
2. Make deca and hepto not possible without a unit hint, maybe I'll add an override later
3. Add radians and degrees. These will need a unit hint to actually see the output though

**Comment by mkhan45** [comment]
Alright after 00a849f this is what happens.

The last one is kind of awkward but I believe that's the same way MathCAD handles it. I'll close the issue since the problem in the title is fixed but let me know if you have suggestions.

![](https://i.imgur.com/NpV6gNe.png)
