### ISSUE TITLE
Weird sign error

### ISSUE THREAD

**Issue by fabianlischka** [mkhan45/CalcuLaTeX#73]
Hi, I've been hit by this weird bug. Smallest example I managed to make is this below.

Input:

```
k = -8
p = 8

lo = 0 + k*p  = ?
hi = 0 - k*p  = ?

k = -8
p = 10

lo = 0 + k*p  = ?
hi = 0 - k*p  = ?
```

Output: 

k=−8
p=8

lo=0+k×p=64     % note: wrong, should be -64
hi=0−k×p=−64  % note: wrong, should be +64

k=−8
p=10

lo=0+k×p=−80   % note: correct
hi=0−k×p=80     % note: correct

**Comment by mkhan45** [comment]
Thanks for the report!

This is pretty concerning so I'll try to get a patch out today.

**Comment by mkhan45** [comment]
Should be fixed, make sure to hard reload the site and/or remove cache so that the new WASM loads
