### ISSUE TITLE
Roots of small numbers

### ISSUE THREAD

**Issue by fabianlischka** [mkhan45/CalcuLaTeX#77]
Hi Mikhail,
thanks for fixing that weird sign bug! Now I calculated some more and stumbled across another issue:

```
4^0.5 = ?
0.25^0.5 = ?
```

Output is:

4^0.500=2   % correct

0.250^{0.500} = 1.581  % incorrect, should be sqrt(1/4) = 1/2 = 0.5

**Comment by mkhan45** [comment]
The fix should be live on calcula.tech in the next hour or so. Thanks for the report!
