### ISSUE TITLE
Improved tests

### ISSUE THREAD

**Issue by mkhan45** [mkhan45/CalcuLaTeX#8]
Including snapshot tests for pdf output?

**Comment by mjhouse** [comment]
You can assign me on this one, if you want.

**Comment by mkhan45** [comment]
@mjhouse by the way, I'm almost certain that there are bugs in `Val`'s Add and Sub implementations, so it's fine for you to PR broken tests if the math checks out.

**Comment by mjhouse** [comment]
Alright, I'll take a look at Val after I finish up Unit.

**Comment by mjhouse** [comment]
@mkhan45 Unless you want this to be an ongoing issue. I think it can be closed. There are a lot more tests now, and they're run automatically before merges to main.

**Comment by mkhan45** [comment]
We still need tests on the LaTeX output. In the past, there have been bugs with LaTeX output getting the prefix on the unit wrong or the power of 10 wrong which is very dangerous since it's not obvious.

**Comment by mkhan45** [comment]
Closed by 619ee02b4e69359094b9725d5ad5b6e042d5aec8 and 0fd6540
