### ISSUE TITLE
More sign shenanigans

### ISSUE THREAD

**Issue by fabianlischka** [mkhan45/CalcuLaTeX#80]
```
X = -10
X*(1) = ?
X/(1) = ?
(X+1)/(1) = ?
(X-1)/(1) = ?
-X = ?
```

gives

```
X*(1) = -10   // yes
X/(1) = 10    // no...
(X+1)/(1) = -9  // yes!
(X-1)/(1) = 11  // no...
-X = ?    // Invalid statement -X = ?
```

I like CalcuLatex, but CalcuLatex doesn't like negative variables... :-)

**Comment by mkhan45** [comment]
I guess CalcuLaTeX just likes keeping things positive :sunglasses: 

I'll probably get to this tomorrow. For future-me reference, the smallest nonworking case is just

`-10/1 = ?`
`-10/-1=?`

**Comment by mkhan45** [comment]
Yeah, for some reason `cargo fetch` on the calcula.tech server wasn't properly fetching the recent version of the CalcuLaTeX library, so not even #75 was in, which is weird because I thought I'd tested it on the remote. The change should be up in a few minutes; make sure to hard reload the site.
